### ISSUE TITLE
Card img issue

### ISSUE THREAD

**Issue by conquestace** [markteekman/accessible-astro-starter#100]
```
<Card title="title" url='' img='/src/assets/img/logo.svg'
              footer={""}
              >
             
              </Card>
```

This does not load the image when `npm run build`

**Comment by markteekman** [comment]
Hey @conquestace, thanks for submitting the issue!

Astro handles images from the `/src` folder a bit differently because of optimizations that they run on it. There's two options:

### 1. Getting your image from the `/public` folder
Images won't be optimized this way and this is how you would use it:

```astro
<Card img='/logo.svg'>
```

### 2. Getting the image from the `/src` folder
You'll have to import the image in the front matter of your file and then access it's `src` attribute:

```astro
---
import logo from '../assets/img/logo.svg'
---

<Card img={logo.src}>
```

Let me know if this solves it for you!

**Comment by conquestace** [comment]
Thank you. I am still a new web-dev and I understand now.

**Comment by markteekman** [comment]
No problem @conquestace and good luck! :)
