### ISSUE TITLE
Theme is visually borked on small screens

### ISSUE THREAD

**Issue by djmtype** [markteekman/accessible-astro-starter#36]
@markteekman After opening the mobile menu toggle, something visually happens. The icon for the mobile toggle has visually vanished although the button is still there and functional. In general, the layout looks off even when returning to the collapsed menu.  

Screencast: https://cloudup.com/czmmaH5b-kA

**Comment by djmtype** [comment]
Upon a quick inspection, it looks like the svg element might be the culprit because if I remove it from within the button, the layout appears fine.

**Comment by djmtype** [comment]
I'm also curious why you've chosen to now use the same menu twice – once as mobile, and the other as desktop. Is there any benefit or just personal preference.

**Comment by markteekman** [comment]
Hey @djmtype! Thanks for submitting the issue 🙂 Weird, I haven't noticed this behavior before, must have been after doing some updates.. I'll check it out. I'm hoping to have some time to get to this in the near future (and your other issue in the Accessible Astro Components repo as well), have been a little too busy lately to do work on the Accessible Astro projects.

As for the double menu, that's a design decision I made in [version 1.3.0](https://github.com/markteekman/accessible-astro-starter/releases/tag/v1.3.0). It introduced an auto responsive feature for the navigation, so that there's no need to custom adjust media queries depending on the number of menu items. It's especially useful when you're using a Headless CMS and menu items are added dynamically. Anyway, the desktop menu is needed to calculate the size for switching between the mobile and desktop menu 😄
